# Form implementation generated from reading ui file 'giris_paneli.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Login_Screen(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(70, 120, 691, 271))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.kullanCAdLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.kullanCAdLabel.setObjectName("kullanCAdLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.kullanCAdLabel)
        self.txt_ka = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txt_ka.setObjectName("txt_ka")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txt_ka)
        self.ifreLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.ifreLabel.setObjectName("ifreLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.ifreLabel)
        self.txt_sfr = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txt_sfr.setObjectName("txt_sfr")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txt_sfr)
        self.btn_giris = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.btn_giris.setObjectName("btn_giris")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.btn_giris)
        self.btn_kayitol = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.btn_kayitol.setObjectName("btn_kayitol")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btn_kayitol)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 50, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.kullanCAdLabel.setText(_translate("MainWindow", "Kullanıcı Adı:"))
        self.ifreLabel.setText(_translate("MainWindow", "Şifre:"))
        self.btn_giris.setText(_translate("MainWindow", "Giriş"))
        self.btn_kayitol.setText(_translate("MainWindow", "Kayıt Ol"))
        self.label.setText(_translate("MainWindow", "GİRİŞ PANELİ"))
